server:
  port: 8080
  servlet:
    context-path: /ltweb

paypal:
  client:
    id: AfQORIPGgUwEako50TWVAG2cqdbkFjLf8_sWzrDcfNZAteQSyErHfZxcdPc8SyRGbi5k41Co-c3jzvT_
    secret: EASwDuUUADdtWRHtTgBoXtkLKbPComIxpC8yN633VuNidq-2Ti1z_lV9hYtcEjnzU9OaPAy1IQK-ePIx
  mode: sandbox

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/travel"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: thaithai12072004@gmail.com
    password: ynqq yiqc lhmj yyuk
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp

avatar:
  upload:
    dir: C:/Users/Dinh Thai/Documents/images/avatar

tour:
  upload:
    dir: C:/Users/Dinh Thai/Documents/images/tour

jwt:
  secret: "u8d7f6g5h4j3k2l1m0n9b8v7c6x5z4a3s2d1f0g9h8j7k6l5m4n3b2v1c0x9z8a7s6d5"
  expiration-ms: 86400000

